---
- hosts: all
  tasks:
      
  - name: Add nginx repository
    apt_repository: repo='ppa:nginx/stable'

  - name: Install utility packages
    apt:
      name:
        - nginx
        - golang-go
        - php-fpm
        - curl
        - letsencrypt
        - git
      state: present
      autoclean: yes
   
  - name: ADD GOPATH
    shell: export GOPATH=/opt/src/

  - name: Mkdir src
    file:
      path: /opt/src
      state: directory

  - name: Cp  main
    template:
      src: templates/back/main.go
      dest: /opt/src/main.go

  - name: build goapp
    shell: go build main.go
    args:
      chdir: /opt/src/
    notify: restart goapp

  - name: Install diff
    template:
      src: templates/back/diff.php        
      dest: /opt/src/diff.php
    notify: restart php

  - name: goapp systemd
    template:
      src: templates/conf/goapp.service 
      dest: /etc/systemd/system/goapp.service
      owner: root
      group: root 
      mode: 0644
    notify:
      - reload systemd
      - enable goapp
      - restart goapp 

  - name: Mkdir www
    file:
      path:  /var/www/denergym.devops.srwx.net/
      state: directory

  - name: Install index
    template:
      src: templates/front/index.html
      dest: /var/www/denergym.devops.srwx.net/index.html
    notify: restart nginx

  - name: Install app.jg 
    template:
      src: templates/front/app.js
      dest: /var/www/denergym.devops.srwx.net/app.js
    notify: restart nginx

  - name: Kick default site
    file: 
      path: /etc/nginx/sites-enabled/default
      state: absent 


  - name: create letsencrypt dir
    file: name=/opt/src/ssl state=directory

  - name: Location 80
    template:
      src: templates/conf/nginx80.j2
      dest: /etc/nginx/sites-enabled/nginx80.j2
      notify: restart nginx

  - name: Location all
    template:
      src: templates/conf/nginxall.j2
      dest: /etc/nginx/sites-enabled/nginxall.j2
      notify: restart nginx

  - name: Mkdir letsencrypt
    file:
      path: /opt/src/ssl
      state: directory

  - name: Mkdir acme letsencrypt
    file:
      path: /var/www/letsencrypt
      state: directory
    
  - name: Create cert letsencrypt
    shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt/  -m {{ letsencrypt_email}} --agree-tos -d {{domain_name}}
    args:
      creates: /etc/letsencrypt/live/{{ domain_name }}
    notify: restart nginx  

  - name: Cronjob  for letsencrypt
    cron:
      name: letsencrypt_renew
      special_time: weekly      
      job: letsencrypt --renew certonly -n --webroot -w /opt/src/ssl -m {{ letsencrypt_email  }} --agree-tos -d {{domain_name}}
    notify: restart nginx

  handlers:
  - name: reload systemd
    systemd: daemon_reload=yes

  - name: enable goapp
    systemd: name=goapp enabled=yes

  - name: restart goapp
    systemd: name=goapp state=restarted

  - name: restart nginx
    systemd: name=nginx state=restarted

  - name: restart php 
    systemd: name=php7.0-fpm state=restarted
